// Common, everyday English words used as practice material. Ordering here
// doesn't matter — the teaching engine filters this pool at runtime down to
// whatever the learner has already unlocked. Wrapped in a Set to shrug off
// any accidental duplicates from a list this size.
const RAW_WORDS = [
  "at", "it", "is", "in", "on", "to", "me", "we", "he", "hi", "am", "an",
  "as", "if", "of", "or", "so", "up", "us", "my", "no", "go", "do", "by",

  "eat", "ate", "tea", "tie", "sit", "sat", "set", "met", "mat", "hot",
  "hat", "ham", "his", "him", "art", "car", "cat", "cot", "cut", "dot",
  "den", "dim", "dry", "day", "hay", "hen", "hit", "hut", "ink", "jam",
  "jar", "jaw", "job", "jog", "joy", "key", "kid", "lab", "lad", "lap",
  "law", "leg", "let", "lid", "lit", "log", "low", "mad", "man", "map",
  "mud", "mug", "nap", "net", "new", "nod", "not", "now", "nut", "oak",
  "our", "out", "owl", "owe", "pad", "pal", "pan", "pat", "paw", "pen",
  "pet", "pin", "pit", "pop", "pot", "pub", "put", "rat", "ran", "rag",
  "ram", "red", "rib", "rid", "rim", "rip", "rob", "rot", "row", "rub",
  "rug", "run", "sad", "sap", "saw", "say", "sea", "see", "she", "sky",
  "sob", "son", "sub", "sum", "sun", "tab", "tag", "tan", "tap", "tar",
  "tax", "ten", "the", "tin", "tip", "toe", "top", "toy", "try", "tub",
  "tug", "use", "van", "vet", "vow", "wag", "war", "was", "wax", "way",
  "web", "wet", "who", "why", "win", "wit", "yes", "yet", "zap", "zip",
  "zoo",

  "team", "mate", "meet", "meat", "tame", "same", "seat", "seed", "seek",
  "seem", "star", "stem", "stir", "mist", "most", "host", "hose", "note",
  "nose", "node", "name", "time", "mine", "mice", "dice", "dine", "dime",
  "dome", "dose", "done", "gone", "cone", "code", "come", "core", "cord",
  "cure", "curl", "hard", "harm", "hare", "herd", "here", "hire", "hurt",
  "kind", "kite", "lake", "lane", "land", "late", "lead", "leaf", "lean",
  "leap", "life", "like", "line", "link", "lion", "list", "load", "loan",
  "lock", "long", "look", "loud", "love", "luck", "made", "mail", "main",
  "make", "male", "mall", "many", "mark", "mask", "meal", "mean", "milk",
  "mild", "mile", "mind", "mint", "miss", "moon", "more", "move", "much",
  "must", "need", "nest", "nice", "nine", "none", "oath", "once", "open",
  "oven", "over", "pace", "pack", "page", "paid", "pain", "pair", "park",
  "part", "past", "path", "peak", "pear", "pick", "pile", "pine", "pink",
  "pipe", "plan", "play", "plot", "plug", "plus", "pond", "pool", "poor",
  "pork", "port", "pose", "post", "pour", "pump", "push", "quiz", "race",
  "rack", "rain", "rare", "rate", "read", "real", "rear", "rely", "rent",
  "rest", "rice", "ride", "ring", "rise", "risk", "road", "roam", "roar",
  "rock", "role", "roll", "roof", "room", "root", "rope", "rose", "rude",
  "rule", "rush", "rust", "sail", "salt", "sand", "save", "seal", "self",
  "sell", "send", "sent", "ship", "shop", "shot", "show", "sick", "side",
  "sign", "silk", "sink", "site", "size", "skin", "skip", "slip", "slot",
  "slow", "snap", "snow", "soap", "soft", "soil", "sold", "sole", "some",
  "song", "soon", "sort", "soul", "soup", "spin", "spot", "stay", "step",
  "stop", "such", "suit", "sunk", "sure", "swim", "tail", "take", "talk",
  "tall", "tank", "tape", "task", "tear", "tell", "tend", "tent", "term",
  "test", "text", "than", "that", "then", "thin", "this", "tick", "tide",
  "tidy", "tile", "till", "tiny", "told", "toll", "tone", "tool", "torn",
  "tour", "town", "trap", "tree", "trim", "trip", "true", "tune", "turn",
  "twin", "type", "unit", "upon", "urge", "used", "user", "vain", "vary",
  "vast", "veil", "vent", "verb", "very", "vest", "view", "vine", "visa",
  "void", "vote", "wage", "wait", "wake", "walk", "wall", "want", "ward",
  "warm", "warn", "wash", "wave", "weak", "wear", "weed", "week", "well",
  "went", "were", "west", "what", "when", "whom", "wide", "wife", "wild",
  "will", "wind", "wine", "wing", "wire", "wise", "wish", "with", "wolf",
  "wood", "wool", "word", "wore", "work", "worn", "wrap", "yard", "yarn",
  "year", "yell", "your", "zero", "zone", "zoom",

  "about", "above", "after", "again", "alarm", "alert", "alike", "alive",
  "allow", "along", "amber", "among", "angle", "apple", "apply", "argue",
  "arise", "armor", "aside", "asset", "audio", "avoid", "awake", "award",
  "aware", "beach", "beard", "beast", "begin", "being", "below", "bench",
  "berry", "birth", "black", "blade", "blame", "blank", "blast", "bless",
  "blind", "block", "blood", "bloom", "board", "boast", "boost", "booth",
  "bound", "brain", "brand", "brave", "bread", "break", "breed", "brick",
  "bride", "brief", "bring", "broad", "broke", "brown", "brush", "build",
  "burst", "cabin", "camel", "candy", "canoe", "cargo", "carry", "catch",
  "cause", "chain", "chair", "chalk", "charm", "chart", "chase", "cheap",
  "check", "cheek", "cheer", "chest", "chief", "child", "chill", "choir",
  "chose", "civic", "claim", "class", "clean", "clear", "climb", "cling",
  "cloak", "clock", "close", "cloth", "cloud", "clown", "coach", "coast",
  "comet", "comic", "couch", "cough", "could", "count", "court", "cover",
  "craft", "crane", "crash", "crawl", "cream", "creek", "creep", "crime",
  "crisp", "cross", "crowd", "crown", "crush", "curve", "dairy", "dance",
  "death", "delay", "depth", "doubt", "draft", "drain", "drama", "dream",
  "dress", "drift", "drill", "drink", "drive", "drown", "earth", "eight",
  "elbow", "elite", "empty", "enjoy", "enter", "equal", "erase", "error",
  "event", "every", "exact", "exist", "fable", "faith", "false", "fault",
  "feast", "fence", "fever", "field", "fifth", "fight", "final", "first",
  "flame", "flash", "fleet", "flesh", "flock", "flood", "floor", "flour",
  "fluid", "flute", "focus", "force", "forge", "forth", "found", "frame",
  "fresh", "front", "frost", "fruit", "funny", "giant", "given", "glass",
  "gleam", "globe", "glory", "gloss", "glove", "goose", "grace", "grade",
  "grain", "grand", "grant", "grape", "graph", "grasp", "grass", "great",
  "greed", "green", "greet", "grief", "grind", "groan", "group", "grown",
  "guard", "guess", "guest", "guide", "habit", "happy", "harsh", "heart",
  "heavy", "hedge", "hobby", "honey", "horse", "hotel", "house", "human",
  "humor", "hunch", "ideal", "index", "inner", "input", "judge", "juice",
  "known", "label", "large", "laugh", "layer", "learn", "least", "leave",
  "lemon", "level", "light", "limit", "local", "logic", "loose", "loyal",
  "lucky", "lunch", "magic", "major", "maker", "march", "marsh", "match",
  "meant", "medal", "merit", "metal", "meter", "might", "minor", "minus",
  "model", "moist", "month", "moral", "motor", "mount", "mouse", "mouth",
  "music", "never", "night", "noble", "noise", "north", "novel", "nurse",
  "occur", "ocean", "offer", "onion", "opera", "orbit", "order", "organ",
  "other", "ought", "outer", "owner", "panel", "panic", "paper", "party",
  "pause", "peace", "pearl", "phase", "phone", "photo", "piano", "piece",
  "pilot", "pitch", "pizza", "place", "plain", "plane", "plant", "plate",
  "plaza", "point", "pouch", "pound", "power", "prize", "proof", "proud",
  "prove", "pulse", "punch", "pupil", "purse", "queen", "quest", "quick",
  "quiet", "quilt", "quite", "radio", "raise", "range", "rapid", "reach",
  "react", "ready", "realm", "rebel", "refer", "reign", "relax", "reply",
  "rider", "ridge", "right", "rigid", "rival", "river", "roast", "robot",
  "rocky", "round", "route", "royal", "rural", "salad", "sauce", "scale",
  "scarf", "scene", "scent", "scope", "score", "scout", "screw", "seven",
  "shade", "shake", "shall", "shame", "shape", "share", "shark", "sharp",
  "shelf", "shell", "shift", "shine", "shiny", "shirt", "shock", "shoot",
  "shore", "short", "shout", "shown", "shrub", "siege", "sight", "silly",
  "since", "skirt", "slate", "sleep", "slide", "slope", "small", "smart",
  "smell", "smile", "smoke", "snack", "snail", "solar", "solid", "solve",
  "sorry", "sound", "south", "space", "spare", "spark", "speak", "spear",
  "speed", "spend", "spent", "spice", "split", "spoke", "spoon", "sport",
  "spray", "staff", "stage", "stain", "stair", "stake", "stamp", "stand",
  "stark", "start", "state", "steak", "steal", "steam", "steel", "steep",
  "steer", "stern", "stick", "stiff", "still", "stock", "stone", "stood",
  "store", "storm", "story", "stove", "strap", "straw", "strip", "stuck",
  "study", "stuff", "style", "sugar", "suite", "sunny", "super", "surge",
  "swear", "sweat", "sweep", "sweet", "swift", "swing", "sword", "table",
  "taste", "teach", "thank", "theme", "there", "these", "thick", "thief",
  "thing", "think", "third", "those", "three", "throw", "thumb", "tiger",
  "tight", "timer", "tired", "title", "toast", "today", "token", "tooth",
  "topic", "torch", "total", "touch", "tough", "tower", "toxic", "trace",
  "track", "trade", "trail", "train", "trait", "treat", "trend", "trial",
  "tribe", "trick", "truck", "truly", "trust", "truth", "tulip", "tutor",
  "twice", "twist", "under", "union", "unite", "until", "upper", "upset",
  "urban", "usage", "usual", "valid", "value", "vapor", "vault", "venue",
  "verse", "video", "vigor", "vital", "vivid", "vocal", "voice", "waist",
  "waste", "watch", "water", "weigh", "weird", "where", "which", "while",
  "white", "whole", "widow", "width", "woman", "world", "worry", "worse",
  "worth", "would", "wound", "woven", "wrist", "write", "wrong", "yield",
  "young", "youth",
];

export const ENGLISH_WORDS: string[] = Array.from(new Set(RAW_WORDS));
